### ISSUE TITLE
issue changing data types in options inspector

### ISSUE THREAD

**Issue by helencarey** [lenses/lenses-react#14]
This may relate to your note in #9, but I keep getting errors when I try to change the datatype from the OptionsInspector in any component.

The local version reports:
<img width="1143" alt="screen shot 2016-04-15 at 10 35 00 pm" src="https://cloud.githubusercontent.com/assets/8650944/14578619/d1f372a0-035a-11e6-90b2-355df2664bbd.png">
(The online version reports the error in ui.js: 1)

Obs, it prevents all sorts of stuff (viz, groupBy) from working.

**Comment by kareemamin** [comment]
This is fixed as well now. Thanks for finding it.
